services:
  ### 🟢 Mosquitto MQTT Broker 1
  mqtt-one:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: mqtt-one
    restart: unless-stopped
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/config/passwd:/etc/mosquitto/passwd
      - ./mosquitto/data:/etc/mosquitto/data
    networks:
      - mqtt_network

  mqtt-two:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: mqtt-two
    restart: unless-stopped
    ports: 
      - "1884:1884"
      - "9002:9002"
    volumes:
      - ./mosquitto/config/mosquitto-2.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/config/passwd:/etc/mosquitto/passwd
      - ./mosquitto/data:/etc/mosquitto/data
    networks:
      - mqtt_network

  ### 🔴 Redis for Message Persistence
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge

volumes:
  redis_data:
    driver: local