services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT Clients will connect to HAProxy at this port
      - "9001:9001"
    volumes:
      - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - mqtt_network
  redis: 
    build: 
      context: ./services/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    ports: 
      - 6379:6379
  mqtt-one:
    build: 
      context: ./services/mosquitto
      dockerfile: Dockerfile
    container_name: mqtt-one
    restart: unless-stopped
    ports: 
      - 1884:1883
      - 9002:9001
    volumes: 
      - ./services/mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./services/mosquitto/config/passwd:/etc/mosquitto/passwd
    networks:
      - mqtt_network
  mqtt-two:
    build: 
      context: ./services/mosquitto
      dockerfile: Dockerfile
    container_name: mqtt-two
    restart: unless-stopped
    ports: 
      - 1885:1883
      - 9003:9001
    volumes: 
      - ./services/mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./services/mosquitto/config/passwd:/etc/mosquitto/passwd
    networks:
      - mqtt_network

networks:
    mqtt_network:
      driver: bridge

