entryPoints:
  mqtt:
    address: ":1883"
  ws:
    address: ":9001"  # WebSocket entry point

providers:
  docker: {
    exposedByDefault: false
  }
  file: {
    filename: "/etc/traefik/traefik.yaml"
  }

tcp:
  routers:
    mqtt:
      rule: "HostSNI(`*`)"
      service: "mqtt-cluster"
      entryPoints:
        - "mqtt"

    mqtt-ws:
      rule: "HostSNI(`*`)"
      service: "mqtt-ws-cluster"
      entryPoints:
        - "ws"

  services:
    mqtt-cluster:
      loadBalancer:
        servers:
          - address: "mqtt-one:1883"
          - address: "mqtt-two:1883"

    mqtt-ws-cluster:
      loadBalancer:
        servers:
          - address: "mqtt-one:9001"
          - address: "mqtt-two:9001"